# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7242936c3ec9acfaeddbb1414054c791f29686cef188198ab6667c270bdfe9d0a0b6656316646c1ad7a23fe88fae77417f12cbffc96001a3e375ed7f46886e0

test:
  secret_key_base: b5c8967b2e965e0e4ff8772d4b5e0e90977de2def5cb148ad22403a2183eaba7e6bd121506ed033d2c40b8dc34200cc786c3c77561a3ff93b1dc1c5ff8f97574

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
